Raise required compiler to rust 1.45
For use of strip_prefix.

    error[E0599]: no method named `strip_prefix` found for type `&std::string::String` in the current scope
       --> src/run.rs:252:41
        |
    252 |                 let dep_name = match en.strip_prefix("dep:") {
        |                                         ^^^^^^^^^^^^